= Installation

== Contents

* xref:#overview[Overview]
* xref:#installation[Installation]
** xref:#install_paths[Installation Paths]
** xref:#install_auto[Automatic Installation]
** xref:#install_manual[Manual Installation]
* xref:#validation_tools[Using Validation Tools]

[[overview]]
== Overview

Installation of the schema files and the catalog file make the resources available to multiple users.   It isn't a requirement, but
it makes working with the schema easier.  Installing the schema also preserves a copy of a known working version compared to
a development version that may not be ready for production use.

[[installation]]
== Installation

[[install_paths]]
=== Installation Paths

For your own personal use, the recommended installation path is `~/.local/share/xml/vtmedia/`.  If you have root access to the host,
and if the schema is going to be used by multiple users, you could also install the files in `/usr/share/xml/vtmedia/`

If you're using **xmllint**, you will need to add the schema to the standard `catalog` file, or create a new catalog file
and reference it with the `XML_CATALOG_FILES` environmental variable.  The automated installation will generate a 
`catalog.xml` file that can be referenced directly, or merged into the system catalog file.

If you're using **Visual Studio Code** with the RedHat XML plugin, you will need to set the path of the catalog file in
the `settings.json` file.  The easiest way to edit that file, is to open the command pallette and type in
`Open User Settings (JSON)`

[source,json]
----
{
  "xml.catalogs": [
      "/User/(username)/.local/share/xml/catalog.xml"
  ]
}
----

There may be other settings in the file, make changes to them as you wish.

[[install_auto]]
=== Automatic Installation

To install the schema, run `make install` from the command line.

[source,console]
----
$ make install
----

The installation path is set in the `DESTDIR` variable in the Makefile, and it can be changed if needed.  If administrative access
is required the `make install` command should be done as the root user.

If there is an existing `catalog.xml` file in the path, the installation will attempt to preserve the file.  If you want to
make manual changes to an existing catalog file you can also use this command:

[source,console]
----
$ make install-no-catalog
----

[[install_manual]]
=== Manual Installation

Manual installation can be acheived with the following commands.

[source,console]
----
$ export DST=~/.local/share/xml
$ mkdir -p $DST/vtmedia
$ cp schemas/*.xsd $DST/vtmedia/
$ cp catalog/catalog.xml $DST/
----

The schema also includes the XML schema and the XLink schema, which are found here.

* https://www.w3.org/2009/01/xml.xsd
* https://www.w3.org/1999/xlink.xsd

[source,console]
----
$ curl https://www.w3.org/2009/01/xml.xsd > $DST/vtmedia/xml.xsd
$ curl https://www.w3.org/1999/xlink.xsd > $DST/vtmedia/xlink.xsd
----

The sample `catalog.xml` file has entries for the XML and XLink namespaces.

[[validation_tools]]
== Using Validation Tools

Assume you have two files:

[souurce,console]
----
$ ls -1 oppenheimer*.xml
oppenheimer-2023-ultrahd.xml
oppenheimer-2023-movie.xml
----

The first file contains the details on the physical media, the second file contains the details on the movie.  The files can be validated
with `xmllint` using the following command.

If the schema files and catalog are installed in a known path, the files can be validated with these commands.

[source,console]
----
$ export XML_CATALOG_FILES=~/.local/share/xml/catalog.xml
$ xmllint --xinclude --schema http://vectortron.com/xml/media/media oppenheimer-2023-ultrahd.xml
----

The command successfully checks the XML syntax, and confirms that the file adheres to the rules of the schema.  Since
the `catalog.xml` file contains references to the schemas installed locally on the host, no network request is made.

If you did not install the schema, it's can be tested by manually specifying the schema location.

[source,console]
----
$ xmllint --xinclude --path ./vtmedia-schema/schemas --schema media-schema.xsd oppenheimer-2023-ultrahd.xml
----
