<?xml version='1.0'?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' elementFormDefault='qualified'>

 <xs:annotation>
  <xs:documentation xml:lang='en-US'>
    Copyright 2025, Chris Josephes

    This work is licensed under the Creative Commons Attribution-ShareAlike
    4.0 International License.

    To view a copy of this license, visit
    http://creativecommons.org/licenses/by-sa/4.0/ or
    send a letter to
    Creative Commons
    PO Box 1866
    Mountain View, CA 94042, USA.
  </xs:documentation>
 </xs:annotation>

 <xs:include schemaLocation='vtm-mod-generic-pnouns-keywords.xsd'/>
 <xs:include schemaLocation='vtm-mod-generic-crew-types.xsd'/>
 <xs:include schemaLocation='vtm-mod-visual-crew-roles.xsd'/>
 <xs:include schemaLocation='vtm-mod-visual-crew-writers.xsd'/>

 <xs:complexType name='DirectorsType'>
  <xs:sequence>
   <xs:element name='director' type='CrewNameType' minOccurs='1' maxOccurs='unbounded'/>
  </xs:sequence>
 </xs:complexType>

 <xs:complexType name='EditorsType'>
  <xs:sequence>
   <xs:element name='editor' type='CrewNameType' minOccurs='1' maxOccurs='unbounded'/>
  </xs:sequence>
 </xs:complexType>

 <xs:complexType name='CinemaphotographersType'>
  <xs:sequence>
   <xs:element name='cinemaphotographer' type='CrewNameType' minOccurs='1' maxOccurs='unbounded'/>
  </xs:sequence>
 </xs:complexType>

 <xs:complexType name='TeamProducersType'>
  <xs:annotation>
   <xs:documentation xml:lang='en-US'>
    A grouping of either co-producers or co-executive producers.
   </xs:documentation>
  </xs:annotation>
  <xs:choice>
   <xs:element name='coProducer' type='CrewNameType' minOccurs='2' maxOccurs='unbounded'/>
   <xs:element name='coExecProducer' type='CrewNameType' minOccurs='2' maxOccurs='unbounded'/>
  </xs:choice>
 </xs:complexType>

 <xs:group name='ProducersGroup'>
  <xs:annotation>
   <xs:documentation xml:lang='en-US'>
    The producers credit group.
   </xs:documentation>
  </xs:annotation>
  <xs:choice>
   <xs:element name='execProducer' type='CrewNameType'/>
   <xs:element name='coExecProducer' type='CrewNameType'/>
   <xs:element name='producer' type='CrewNameType'/>
   <xs:element name='assocProducer' type='CrewNameType'/>
   <xs:element name='assistProducer' type='CrewNameType'/>
   <xs:element name='lineProducer' type='CrewNameType'/>
   <xs:element name='coProducer' type='CrewNameType'/>
   <xs:element name='team' type='TeamProducersType'/>
  </xs:choice>
 </xs:group>

 <xs:complexType name='ProducersType'>
  <xs:annotation>
   <xs:documentation xml:lang='en-US'>
    Contains at least one of any of the elements in the
    Producers group.
   </xs:documentation>
  </xs:annotation>
  <xs:choice>
   <xs:group ref='ProducersGroup' minOccurs='1' maxOccurs='unbounded'/>
  </xs:choice>
 </xs:complexType>

 <xs:group name='ArtDirectorGroup'>
  <xs:annotation>
   <xs:documentation xml:lang='en-US'>
    Job structure for art directors.
   </xs:documentation>
  </xs:annotation>
  <xs:choice>
   <xs:element name='artDirector' type='CrewNameType'/>
   <xs:element name='assistArtDirector' type='CrewNameType'/>
   <xs:element name='supervisingArtDirector' type='CrewNameType'/>
   <xs:element name='seniorArtDirector' type='CrewNameType'/>
  </xs:choice>
 </xs:group>

 <xs:complexType name='ArtDeptType'>
  <xs:sequence minOccurs='1'>
   <xs:element name='productionDesigner' type='CrewNameType' minOccurs='0' maxOccurs='unbounded'/>
   <xs:group ref='ArtDirectorGroup' minOccurs='0' maxOccurs='unbounded'/>
   <xs:element name='setDecorator' type='CrewNameType' minOccurs='0' maxOccurs='unbounded'/>
  </xs:sequence>
 </xs:complexType>

 <xs:complexType name='WardrobeDeptType'>
  <xs:sequence minOccurs='1'>
   <xs:element name='costumeDesigner' type='CrewNameType' minOccurs='0' maxOccurs='unbounded'/>
   <xs:element name='wardrobe' type='CrewNameType' minOccurs='0' maxOccurs='unbounded'/>
  </xs:sequence>
 </xs:complexType>

 <xs:complexType name='CastingType'>
  <xs:sequence minOccurs='1'>
   <xs:element name='director' type='CrewNameType' minOccurs='0' maxOccurs='unbounded'/>
   <xs:element name='consultant' type='CrewNameType' minOccurs='0' maxOccurs='unbounded'/>
   <xs:element name='casting' type='CrewNameType' minOccurs='0' maxOccurs='unbounded'/>
  </xs:sequence>
 </xs:complexType>

 <xs:group name='MusicGroup'>
  <xs:annotation>
   <xs:documentation xml:lang='en-US'>
    Job selection for the music department.
   </xs:documentation>
  </xs:annotation>
  <xs:choice>
   <xs:element name='composer' type='CrewPersonOrGroupType'/>
   <xs:element name='conductor' type='CrewPersonOrGroupType'/>
   <xs:element name='music' type='CrewPersonOrGroupType'/>
  </xs:choice>
 </xs:group>

 <xs:complexType name='MusicType'>
  <xs:annotation>
   <xs:documentation xml:lang='en-US'>
    Crew members from the music department
   </xs:documentation>
  </xs:annotation>
  <xs:sequence>
   <xs:group ref='MusicGroup' minOccurs='1' maxOccurs='unbounded'/>
  </xs:sequence>
 </xs:complexType>


 <xs:complexType name='CastType'>
  <xs:sequence>
   <xs:element name='role' type='RoleType' minOccurs='1' maxOccurs='unbounded'/>
  </xs:sequence>
 </xs:complexType>

 <xs:complexType name='CrewType'>
  <xs:sequence>
   <xs:element name='directors' type='DirectorsType' minOccurs='0' maxOccurs='1'/>
   <xs:element name='writers' type='WritersType' minOccurs='0' maxOccurs='1'/>
   <xs:element name='producers' type='ProducersType' minOccurs='0' maxOccurs='1'/>
   <xs:element name='editors' type='EditorsType' minOccurs='0' maxOccurs='1'/>
   <xs:element name='cinemaphotographers' type='CinemaphotographersType' minOccurs='0' maxOccurs='1'/>
   <xs:element name='music' type='MusicType' minOccurs='0' maxOccurs='1'/>
   <xs:element name='artDept' type='ArtDeptType' minOccurs='0' maxOccurs='1'/>
   <xs:element name='wardrobe' type='WardrobeDeptType' minOccurs='0' maxOccurs='1'/>
   <xs:element name='casting' type='CastingType' minOccurs='0' maxOccurs='1'/>
   <xs:element name='cast' type='CastType' minOccurs='0' maxOccurs='1'/>
  </xs:sequence>
 </xs:complexType>


</xs:schema>
